name: Deploy to GitHub Releases

on:
  push:
    branches: [master]
    pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      # Set environment variables
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          el=$(grep -n '## \[' CHANGELOG.md | awk -F ':' 'NR == 2  { print $1 }')
          CHANGELOG=$(awk "NR > 2 && NR < $el" CHANGELOG.md)
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          
          echo "::set-output name=changelog::$CHANGELOG"
